const words_List = [
    { id: 1, word: "apple", hint: "A fruit that is red or green" },
    { id: 2, word: "banana", hint: "A long yellow fruit" },
    { id: 3, word: "carrot", hint: "An orange vegetable" },
    { id: 4, word: "dog", hint: "A loyal pet" },
    { id: 5, word: "elephant", hint: "A large gray animal with a trunk" },
    { id: 6, word: "flower", hint: "A part of a plant that blossoms" },
    { id: 7, word: "guitar", hint: "A musical instrument with strings" },
    { id: 8, word: "house", hint: "A place where people live" },
    { id: 9, word: "island", hint: "A piece of land surrounded by water" },
    { id: 10, word: "jungle", hint: "A dense forest in tropical areas" },
    { id: 11, word: "kite", hint: "A flying object on a string" },
    { id: 12, word: "lemon", hint: "A sour yellow fruit" },
    { id: 13, word: "mountain", hint: "A large natural elevation of the earth's surface" },
    { id: 14, word: "notebook", hint: "A book for writing notes" },
    { id: 15, word: "ocean", hint: "A vast body of saltwater" },
    { id: 16, word: "pencil", hint: "A tool for writing or drawing" },
    { id: 17, word: "queen", hint: "A female monarch or ruler" },
    { id: 18, word: "river", hint: "A natural flow of water" },
    { id: 19, word: "sun", hint: "The star at the center of our solar system" },
    { id: 20, word: "tree", hint: "A tall plant with a trunk and branches" },
    { id: 21, word: "umbrella", hint: "A device for protection from rain or sun" },
    { id: 22, word: "violin", hint: "A musical instrument with four strings" },
    { id: 23, word: "water", hint: "A clear liquid essential for life" },
    { id: 24, word: "xylophone", hint: "A musical instrument with wooden bars" },
    { id: 25, word: "yarn", hint: "A long thread used for knitting" },
    { id: 26, word: "zebra", hint: "A black-and-white striped animal" },
    { id: 27, word: "anchor", hint: "A heavy object to hold a ship in place" },
    { id: 28, word: "butterfly", hint: "An insect with colorful wings" },
    { id: 29, word: "camera", hint: "A device for taking photographs" },
    { id: 30, word: "diamond", hint: "A precious gemstone" },
    { id: 31, word: "eclipse", hint: "When one celestial body obscures another" },
    { id: 32, word: "forest", hint: "A large area covered with trees" },
    { id: 33, word: "globe", hint: "A spherical model of the Earth" },
    { id: 34, word: "helicopter", hint: "A flying vehicle with rotating blades" },
    { id: 35, word: "iceberg", hint: "A large floating mass of ice" },
    { id: 36, word: "jacket", hint: "A type of outerwear" },
    { id: 37, word: "kangaroo", hint: "An Australian marsupial" },
    { id: 38, word: "laptop", hint: "A portable computer" },
    { id: 39, word: "microphone", hint: "A device for amplifying sound" },
    { id: 40, word: "needle", hint: "A thin tool for sewing" },
    { id: 41, word: "octopus", hint: "A sea creature with eight arms" },
    { id: 42, word: "parrot", hint: "A colorful bird that can mimic speech" },
    { id: 43, word: "quill", hint: "A feather used as a writing tool" },
    { id: 44, word: "robot", hint: "A machine capable of performing tasks" },
    { id: 45, word: "satellite", hint: "An object orbiting a planet" },
    { id: 46, word: "telescope", hint: "A device for viewing distant objects" },
    { id: 47, word: "uniform", hint: "Standardized clothing for a group" },
    { id: 48, word: "volcano", hint: "A mountain that erupts lava" },
    { id: 49, word: "whale", hint: "A large marine mammal" },
    { id: 50, word: "x-ray", hint: "A type of electromagnetic radiation" }
];
export default words_List;